

services:
  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql   # Updated mount point
      - ./db-init-scripts:/docker-entrypoint-initdb.d  # SQL init scripts

  # Backend Service (FastAPI)
  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  # Frontend Service (React)
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  postgres_data: